server:
  port: 8080
spring:
  application:
    name: example-spring-boot-provider

nacos:
  discovery:
    server-addr: 127.0.0.1:8848

dubbo:
  application:
    name: example-spring-boot-provider
  registry:
    address: nacos://localhost:8848