server:
  port: 8080
spring:
  application:
    name: example-spring-boot-provider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://qi-rpc:3306/rpc_test?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: Crq13709390514..

nacos:
  discovery:
    server-addr: 127.0.0.1:8848

dubbo:
  application:
    name: example-spring-boot-provider
  registry:
    address: nacos://nacos:8848